import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "@/providers/Global";
import { ThemeProvider } from "@/components/theme-provider";
import AuthProvider from "@/providers/AuthProvider";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BizFloww",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <GlobalProvider>
          <body
            className={`${inter.className} relative h-full font-sans antialiased`}
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <NavBar />

              <main className="relative flex flex-col min-h-screen">
                <div className="flex-grow flex-1">{children}</div>
              </main>
            </ThemeProvider>
          </body>
        </GlobalProvider>
      </AuthProvider>
    </html>
  );
}
